version: "3"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
  web:
    image: nginx:alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    depends_on:
      - php
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
  node:
    image: node:alpine
    user: node
    working_dir: /assets
    volumes:
      - ./:/assets
    command: npm run watch
  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data
volumes:
  mysqldata:
  redisdata:
